name: Handle Metadata Dispatch

on:
  repository_dispatch:
    types: [new-release]

jobs:
  handle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout metadata repo
        uses: actions/checkout@v4

      - name: Parse payload
        id: parse
        run: |
            echo '${{ toJson(github.event.client_payload) }}' > payload.json
            jq . payload.json

            repo=$(jq -r .repo payload.json)
            tag=$(jq -r .tag payload.json)
            REPO_NAME="${repo##*/}"

            echo "REPO=$repo" >> $GITHUB_ENV
            echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
            echo "TAG=$tag" >> $GITHUB_ENV

            IFS='.' read -r MAJOR MINOR PATCH <<< "${tag#v}"
            echo "MAJOR=$MAJOR" >> $GITHUB_ENV
            echo "MINOR=$MINOR" >> $GITHUB_ENV
            echo "PATCH=$PATCH" >> $GITHUB_ENV

      - name: Debug ENV values
        run: |
            echo "REPO_NAME=$REPO_NAME"
            echo "TAG=$TAG"
            echo "MAJOR=$MAJOR"
            echo "MINOR=$MINOR"
            echo "PATCH=$PATCH"

      - name: Fetch Schemas
        run: |
            AUTH="Authorization: Bearer ${{ secrets.METADATA_REPO_PAT }}"
            for file in config.json baton_capabilities.json; do
                url="https://raw.githubusercontent.com/$REPO/$TAG/$file"
                tmp=$(mktemp)

                echo "Fetching $file..."
                status=$(curl -s -o "$tmp" -w "%{http_code}" -H "$AUTH" "$url")

                if [ "$status" -ne 200 ]; then
                    echo "❌ Failed to fetch $file from $url (status $status)"
                    echo "--- Response ---"
                    cat "$tmp"
                    echo "----------------"
                    exit 1
                fi

                mv "$tmp" "$file"
                echo "✅ Downloaded $file"
            done

      - name: Write metadata file
        run: |
            rm payload.json
            mkdir -p "metadata/$REPO/$MAJOR/$MINOR"

            jq -n \
                --argjson config "$(cat config.json)" \
                --argjson baton_capabilities "$(cat baton_capabilities.json)" \
                '{config: $config, baton_capabilities: $baton_capabilities}' \
                > "metadata/TRAINFACED/$REPO/$MAJOR/$MINOR/$PATCH.json"
            rm config.json baton_capabilities.json

      - name: Compute safe branch name
        id: branch
        run: |
            safe_repo="${REPO//\//-}"
            echo "branch=metadata-${safe_repo}-${VERSION}" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.METADATA_REPO_PAT }}
            commit-message: "Add metadata for ${{ env.REPO }}@${{ env.VERSION }}"
            title: "Add metadata for ${{ env.REPO }}@${{ env.VERSION }}"
            body: |
                This PR contains configuration metadata for:
                - Repo: ${{ env.REPO }}
                - Version: ${{ env.VERSION }}
            branch: ${{ steps.branch.outputs.branch }}