name: Handle Metadata Dispatch

on:
  repository_dispatch:
    types: [new-release]

jobs:
  handle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout metadata repo
        uses: actions/checkout@v4

      - name: Parse payload
        id: parse
        run: |
            echo '${{ toJson(github.event.client_payload) }}' > payload.json
            jq . payload.json
            repo=$(jq -r .repo payload.json)
            tag=$(jq -r .tag payload.json)
            echo "REPO=$repo" >> $GITHUB_ENV
            echo "TAG=$tag" >> $GITHUB_ENV
            echo "SENDER=${{ github.event.client_payload.sender }}" >> $GITHUB_ENV

            IFS='.' read -r MAJOR MINOR PATCH <<< "${TAG#v}"
            echo "TAG=$TAG" >> $GITHUB_ENV
            echo "MAJOR=$MAJOR" >> $GITHUB_ENV
            echo "MINOR=$MINOR" >> $GITHUB_ENV
            echo "PATCH=$PATCH" >> $GITHUB_ENV
            REPO_NAME="${repo##*/}"
            echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Debug ENV values
        run: |
            echo "REPO_NAME=$REPO_NAME"
            echo "TAG=$TAG"
            echo "SENDER=$SENDER"
            echo "MAJOR=$MAJOR"
            echo "MINOR=$MINOR"
            echo "PATCH=$PATCH"

      - name: Fetch Schemas
        run: |
            curl -s -H "Authorization: Bearer ${{ secrets.METADATA_REPO_PAT }}" \
                -o config.json \
                https://raw.githubusercontent.com/TRAINFACED/${REPO}/${TAG}/config.json

            curl -s -H "Authorization: Bearer ${{ secrets.METADATA_REPO_PAT }}" \
                -o baton_capabilities.json \
                https://raw.githubusercontent.com/TRAINFACED/${REPO}/${TAG}/baton_capabilities.json

      - name: Write metadata file
        run: |
            rm payload.json
            mkdir -p "metadata/$REPO/$MAJOR/$MINOR"

            jq -n \
                --argjson config "$(cat config.json)" \
                --argjson baton_capabilities "$(cat baton_capabilities.json)" \
                '{config: $config, baton_capabilities: $baton_capabilities}' \
                > "metadata/TRAINFACED/$REPO/$MAJOR/$MINOR/$PATCH.json"
            rm config.json baton_capabilities.json

      - name: Compute safe branch name
        id: branch
        run: |
            safe_repo="${REPO//\//-}"
            echo "branch=metadata-${safe_repo}-${VERSION}" >> $GITHUB_OUTPUT

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.METADATA_REPO_PAT }}
            commit-message: "Add metadata for ${{ env.REPO }}@${{ env.VERSION }}"
            title: "Add metadata for ${{ env.REPO }}@${{ env.VERSION }}"
            body: |
                This PR contains configuration metadata for:
                - Repo: ${{ env.REPO }}
                - Version: ${{ env.VERSION }}
            branch: ${{ steps.branch.outputs.branch }}